# Generated by Django 5.2.8 on 2025-11-26 15:51

import apps.posts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_postimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postimage',
            name='image',
            field=models.ImageField(upload_to='post/images', validators=[apps.posts.validators.validate_file_size]),
        ),
    ]
