# Generated by Django 5.2.8 on 2025-12-04 10:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_postresponse'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='postresponse',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='post',
            name='dislikes',
        ),
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
        migrations.AlterField(
            model_name='postresponse',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='posts.post'),
        ),
        migrations.AlterField(
            model_name='postresponse',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_responses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='postresponse',
            constraint=models.UniqueConstraint(fields=('user', 'post'), name='unique_user_post_response'),
        ),
    ]
