# Generated by Django 5.2.10 on 2026-01-20 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_user_gender_alter_user_birth_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="gender",
        ),
    ]
